apiVersion: v1
kind: Service
metadata:
  name: web-socket-service
  namespace: messenger
  labels:
    app: web-socket-service
spec:
  type: ClusterIP
  selector:
    app: web-socket-service
  ports:
    - name: http
      port: 80
      targetPort: 8086