package enums;

public enum GroupChatEventType {

    GROUP_CHAT_CREATED,
    GROUP_CHAT_ADDED_MEMBERS,
    GROUP_CHAT_REMOVED_MEMBERS,
    GROUP_CHAT_CHANGED_ROLES,
    GROUP_CHAT_CHANGED_INFO,
    GROUP_CHAT_DELETED,
}
