services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  postgres_user:
    image: postgres:16
    container_name: postgres_user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_user:/var/lib/postgresql/data

  postgres_sso:
    image: postgres:16
    container_name: postgres_sso
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sso_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_sso:/var/lib/postgresql/data

  postgres_personal-chat:
    image: postgres:16
    container_name: postgres_personal-chat
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal-chat_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_personal-chat:/var/lib/postgresql/data

  postgres_group-chat:
    image: postgres:16
    container_name: postgres_group-chat-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: group-chat_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_group-chat:/var/lib/postgresql/data

  postgres_message:
    image: postgres:16
    container_name: postgres_message
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: message_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_message:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper_z
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - '9093:9093'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - postgres_user
      - redis
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_user:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
      - "6565:6565"

  personal-chat-service:
    build:
      context: ./personal-chat-service
      dockerfile: Dockerfile
    container_name: personal-chat-service
    depends_on:
      - postgres_personal-chat
      - redis
      - kafka
      - user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_personal-chat:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8083
      GRPC_CLIENT_USER_SERVICE_ADDRESS: static://user-service:6565
    ports:
      - "8083:8083"
      - "6567:6567"

  group-chat-service:
    build:
      context: ./group-chat-service
      dockerfile: Dockerfile
    container_name: group-chat-service
    depends_on:
      - postgres_group-chat
      - redis
      - kafka
      - user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_group-chat:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8084
      GRPC_CLIENT_USER_SERVICE_ADDRESS: static://user-service:6565
    ports:
      - "8084:8084"
      - "6566:6566"

  message-service:
    build:
      context: ./message-service
      dockerfile: Dockerfile
    container_name: message-service
    depends_on:
      - postgres_message
      - redis
      - kafka
      - user-service
      - personal-chat-service
      - group-chat-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_message:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8085
      GRPC_CLIENT_USER_SERVICE_ADDRESS: static://user-service:6565
      GRPC_CLIENT_PERSONAL_CHAT_SERVICE_ADDRESS: static://personal-chat-service:6567
      GRPC_CLIENT_GROUP_CHAT_SERVICE_ADDRESS: static://group-chat-service:6566
    ports:
      - "8085:8085"

volumes:
  postgres_user:
  postgres_sso:
  postgres_personal-chat:
  postgres_group-chat:
  postgres_message:
  redis: