services:
  redis:
    image: redis:alpine
    container_name: redis_data
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres_user:
    image: postgres:16
    container_name: postgres_user-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_user:/var/lib/postgresql/data

  postgres_sso:
    image: postgres:16
    container_name: postgres_sso-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sso_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_sso:/var/lib/postgresql/data

  postgres_personal-chat:
    image: postgres:16
    container_name: postgres_personal-chat-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal-chat_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_personal-chat:/var/lib/postgresql/data

  postgres_group-chat:
    image: postgres:16
    container_name: postgres_group-chat-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: group-chat_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_group-chat:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper_z
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka_k
    hostname: kafka
    ports:
      - '9093:9093'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper

volumes:
  postgres_user:
  postgres_sso:
  postgres_personal-chat:
  postgres_group-chat:
  redis_data: