apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: messenger
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
    - name: grpc
      port: 6565
      targetPort: 6565