apiVersion: v1
kind: ConfigMap
metadata:
  name: web-socket-service-config
  namespace: messenger
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
  SPRING_REDIS_HOST: redis
  SPRING_REDIS_PORT: "6379"
  SERVER_PORT: "8086"