apiVersion: v1
kind: Service
metadata:
  name: web-socket-service
  namespace: messenger
spec:
  type: ClusterIP
  selector:
    app: web-socket-service
  ports:
    - port: 8086
      targetPort: 8086