apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: messenger
  labels:
    app: message-service
spec:
  selector:
    app: message-service
  ports:
    - name: http
      port: 80
      targetPort: 8085
    - name: grpc
      port: 6568
      targetPort: 6568