apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: messenger
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: message-service
  ports:
    - name: http
      port: 80
      targetPort: 8085
    - name: grpc
      port: 6568
      targetPort: 6568