apiVersion: v1
kind: Service
metadata:
  name: postgres-group-chat
  namespace: messenger
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres-group-chat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-group-chat
  namespace: messenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-group-chat
  template:
    metadata:
      labels:
        app: postgres-group-chat
    spec:
      containers:
        - name: postgres-group-chat
          image: postgres:16
          env:
            - name: POSTGRES_GROUP_CHAT
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "group-chat_db"
          ports:
            - containerPort: 5432