apiVersion: v1
kind: Service
metadata:
  name: postgres-user
  namespace: messenger
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user
  namespace: messenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
        - name: postgres-user
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "user_db"
          ports:
            - containerPort: 5432