apiVersion: v1
kind: Service
metadata:
  name: postgres-personal-chat
  namespace: messenger
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres-personal-chat
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-personal-chat
  namespace: messenger
spec:
  serviceName: "postgres-personal-chat"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-personal-chat
  template:
    metadata:
      labels:
        app: postgres-personal-chat
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "personal-chat_db"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi