apiVersion: v1
kind: Service
metadata:
  name: personal-chat-service
  namespace: messenger
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: personal-chat-service
  ports:
    - name: http
      port: 80
      targetPort: 8083
    - name: grpc
      port: 6567
      targetPort: 6567