apiVersion: v1
kind: Service
metadata:
  name: personal-chat-service
  namespace: messenger
spec:
  selector:
    app: personal-chat-service
  ports:
    - name: http
      port: 80
      targetPort: 8083
    - name: grpc
      port: 6567
      targetPort: 6567