syntax = "proto3";
package message;

import "google/protobuf/timestamp.proto";

service MessageService {
  rpc SendMessage(SendMessageRequest) returns (MessageResult);
  rpc MarkAsRead(MarkAsReadRequest) returns (MessageResult);
}

message MessageResult {
  oneof result {
    MessageResponse success = 1;
    ErrorResponse error = 2;
  }
}

message MessageResponse {
  int64 id = 1;
  int64 chat_id = 2;
  ChatType chat_type = 3;
  int64 sender_id = 4;
  MessageType message_type = 5;

  oneof payload {
    string text = 6;
    int64 media_id = 7;
  }

  google.protobuf.Timestamp created_at = 8;
  optional google.protobuf.Timestamp edited_at = 9;
  optional google.protobuf.Timestamp read_at = 10;
}

message ErrorResponse {
  int32 error_code = 1;
  string error = 2;
  string message = 3;
  google.protobuf.Timestamp timestamp = 4;
}

message SendMessageRequest {
  int64 sender_id = 1;
  int64 chat_id = 2;
  ChatType chat_type = 3;
  MessageType message_type = 4;

  oneof payload {
    string text = 5;
    int64 media_id = 6;
  }
}

message MarkAsReadRequest {
  int64 reader_id = 1;
  int64 id = 2;
  int64 chat_id = 3;
  ChatType chat_type = 4;
}

enum ChatType {
  PERSONAL = 0;
  GROUP = 1;
}

enum MessageType {
  TEXT = 0;
  MEDIA = 1;
}