syntax = "proto3";
package personal_chat;

service PersonalChatService {
  rpc ValidateUserIsMemberOfPersonalChat(ValidateUserIsMemberOfPersonalChatRequest)
      returns (ValidateUserIsMemberOfPersonalChatResponse);
  rpc GetAllPersonalChatMembers(GetAllPersonalChatMembersRequest) returns (GetAllPersonalChatMembersResponse);
}

message ValidateUserIsMemberOfPersonalChatRequest {
  int64 userId = 1;
  int64 chatId = 2;
}

message ValidateUserIsMemberOfPersonalChatResponse {
  int64 userId = 1;
  int64 chatId = 2;
  bool isMember = 3;
}

message GetAllPersonalChatMembersRequest {
  int64 chatId = 1;
}

message GetAllPersonalChatMembersResponse {
  repeated int64 userId = 1;
}
