syntax = "proto3";
package user;

service UserService {
  rpc ValidateUsersExist(ValidateUsersExistRequest) returns (UsersExistResponse);
  rpc UsersInfo(UsersInfoRequest) returns (UsersInfoResponse);
}

message ValidateUsersExistRequest {
  repeated int64 userIds = 1;
}

message UsersExistResponse {
  message UserExistence {
    int64 userId = 1;
    bool exists = 2;
    bool isActive = 3;
  }
  repeated UserExistence results = 1;
}

message UsersInfoRequest {
  repeated int64 userIds = 1;
}

message UsersInfoResponse {
  message UserInfo {
    int64 userId = 1;
    string username = 2;
    int64 avatarId = 3;
  }
  repeated UserInfo results = 1;
}