server:
  port: 8086

spring:
  application:
    name: web-socket-service

frontend:
  port: "http://localhost:8000"

grpc:
  client:
    message-service:
      address: static://localhost:6568
      negotiation-type: plaintext

redis:
  ttl: 30

jwt:
  secret-key: i3mOlQItCJ7wSbkiMAUaVBk8NZz4LjOlvIMMGXpwFeUHKMrdMpWygKWLxuFs9NVV