server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: group-chat-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres_group-chat:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      max-lifetime: 300000
      idle-timeout: 30000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db.migrations/db.migrations.yaml

  cache:
    type: redis
    redis:
      time-to-live: 3m
      cache-null-values: false

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9093}
    consumer:
      group-id: group-chat-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dto.event,*"
        spring.json.value.default.type: "dto.event.MessageShortEvent"
        spring.json.use.type.headers: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

grpc:
  server:
    port: ${GRPC_SERVER_PORT:6566}

  client:
    user-service:
      address: dns:///user-service:6565
      negotiation-type: plaintext
      default-load-balancing-policy: round_robin

redis:
  ttl: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true