apiVersion: v1
kind: ConfigMap
metadata:
  name: sso-service-config
  namespace: messenger
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-sso:5432/postgres
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
  SPRING_REDIS_HOST: redis
  SERVER_PORT: "8081"