apiVersion: v1
kind: Service
metadata:
  name: sso-service
  namespace: messenger
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: sso-service
  ports:
    - port: 80
      targetPort: 8081