apiVersion: v1
kind: ConfigMap
metadata:
  name: media-service-config
  namespace: messenger
data:
  SPRING_PROFILES_ACTIVE: k8s
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-media:5432/postgres
  SERVER_PORT: "8087"
  S3_BUCKET: messenger-media-backet
  S3_REGION: ru-central1
  S3_ENDPOINT: https://storage.yandexcloud.net