server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: sso-service
          uri: http://sso-service:8081
          predicates:
            - Path=/auth/**

        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: user-service-profile
          uri: lb://user-service
          predicates:
            - Path=/profile/**

        - id: personal-chat-service
          uri: http://personal-chat-service:8083
          predicates:
            - Path=/chats/personal/**

        - id: group-chat-service-chats
          uri: http://group-chat-service:8084
          predicates:
            - Path=/chats/group/**

        - id: group-chat-service-members
          uri: http://group-chat-service:8084
          predicates:
            - Path=/chats/group/members/**

        - id: web-socket-service
          uri: ws://web-socket-service:8086
          predicates:
            - Path=/ws/chat/**



        - id: sso-service-docs
          uri: http://sso-service:8081
          predicates:
            - Path=/sso-service/v3/api-docs
          filters:
            - RewritePath=/sso-service/(?<segment>.*), /$\{segment}

        - id: user-service-docs
          uri: http://user-service:8082
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: personal-chat-service-docs
          uri: http://personal-chat-service:8083
          predicates:
            - Path=/personal-chat-service/v3/api-docs
          filters:
            - RewritePath=/personal-chat-service/(?<segment>.*), /$\{segment}

        - id: group-chat-service-docs
          uri: http://group-chat-service:8084
          predicates:
            - Path=/group-chat-service/v3/api-docs
          filters:
            - RewritePath=/group-chat-service/(?<segment>.*), /$\{segment}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: sso-service
        url: /sso-service/v3/api-docs
      - name: personal-chat-service
        url: /personal-chat-service/v3/api-docs
      - name: group-chat-service
        url: /group-chat-service/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

jwt:
  secret-key: i3mOlQItCJ7wSbkiMAUaVBk8NZz4LjOlvIMMGXpwFeUHKMrdMpWygKWLxuFs9NVV