server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: sso-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: user-service-users
          uri: http://localhost:8082
          predicates:
            - Path=/users/**

        - id: user-service-profile
          uri: http://localhost:8082
          predicates:
            - Path=/profile/**

        - id: personal-chat-service
          uri: http://localhost:8083
          predicates:
            - Path=/chats/personal/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

jwt:
  secret-key: i3mOlQItCJ7wSbkiMAUaVBk8NZz4LjOlvIMMGXpwFeUHKMrdMpWygKWLxuFs9NVV