// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personal_chat.proto

// Protobuf Java Version: 3.25.1
package personal_chat;

public final class PersonalChat {
  private PersonalChat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ValidateUserIsMemberOfPersonalChatRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:personal_chat.ValidateUserIsMemberOfPersonalChatRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>int64 chatId = 2;</code>
     * @return The chatId.
     */
    long getChatId();
  }
  /**
   * Protobuf type {@code personal_chat.ValidateUserIsMemberOfPersonalChatRequest}
   */
  public static final class ValidateUserIsMemberOfPersonalChatRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:personal_chat.ValidateUserIsMemberOfPersonalChatRequest)
      ValidateUserIsMemberOfPersonalChatRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValidateUserIsMemberOfPersonalChatRequest.newBuilder() to construct.
    private ValidateUserIsMemberOfPersonalChatRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValidateUserIsMemberOfPersonalChatRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ValidateUserIsMemberOfPersonalChatRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return personal_chat.PersonalChat.internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return personal_chat.PersonalChat.internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest.class, personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_ = 0L;
    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int CHATID_FIELD_NUMBER = 2;
    private long chatId_ = 0L;
    /**
     * <code>int64 chatId = 2;</code>
     * @return The chatId.
     */
    @java.lang.Override
    public long getChatId() {
      return chatId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (chatId_ != 0L) {
        output.writeInt64(2, chatId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (chatId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, chatId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest)) {
        return super.equals(obj);
      }
      personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest other = (personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (getChatId()
          != other.getChatId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + CHATID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChatId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code personal_chat.ValidateUserIsMemberOfPersonalChatRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:personal_chat.ValidateUserIsMemberOfPersonalChatRequest)
        personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return personal_chat.PersonalChat.internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return personal_chat.PersonalChat.internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest.class, personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest.Builder.class);
      }

      // Construct using personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = 0L;
        chatId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return personal_chat.PersonalChat.internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatRequest_descriptor;
      }

      @java.lang.Override
      public personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest getDefaultInstanceForType() {
        return personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest.getDefaultInstance();
      }

      @java.lang.Override
      public personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest build() {
        personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest buildPartial() {
        personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest result = new personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.chatId_ = chatId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest) {
          return mergeFrom((personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest other) {
        if (other == personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getChatId() != 0L) {
          setChatId(other.getChatId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                chatId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <code>int64 userId = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private long chatId_ ;
      /**
       * <code>int64 chatId = 2;</code>
       * @return The chatId.
       */
      @java.lang.Override
      public long getChatId() {
        return chatId_;
      }
      /**
       * <code>int64 chatId = 2;</code>
       * @param value The chatId to set.
       * @return This builder for chaining.
       */
      public Builder setChatId(long value) {

        chatId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 chatId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chatId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:personal_chat.ValidateUserIsMemberOfPersonalChatRequest)
    }

    // @@protoc_insertion_point(class_scope:personal_chat.ValidateUserIsMemberOfPersonalChatRequest)
    private static final personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest();
    }

    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValidateUserIsMemberOfPersonalChatRequest>
        PARSER = new com.google.protobuf.AbstractParser<ValidateUserIsMemberOfPersonalChatRequest>() {
      @java.lang.Override
      public ValidateUserIsMemberOfPersonalChatRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ValidateUserIsMemberOfPersonalChatRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValidateUserIsMemberOfPersonalChatRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValidateUserIsMemberOfPersonalChatResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:personal_chat.ValidateUserIsMemberOfPersonalChatResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>int64 chatId = 2;</code>
     * @return The chatId.
     */
    long getChatId();

    /**
     * <code>bool isMember = 3;</code>
     * @return The isMember.
     */
    boolean getIsMember();
  }
  /**
   * Protobuf type {@code personal_chat.ValidateUserIsMemberOfPersonalChatResponse}
   */
  public static final class ValidateUserIsMemberOfPersonalChatResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:personal_chat.ValidateUserIsMemberOfPersonalChatResponse)
      ValidateUserIsMemberOfPersonalChatResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValidateUserIsMemberOfPersonalChatResponse.newBuilder() to construct.
    private ValidateUserIsMemberOfPersonalChatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValidateUserIsMemberOfPersonalChatResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ValidateUserIsMemberOfPersonalChatResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return personal_chat.PersonalChat.internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return personal_chat.PersonalChat.internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse.class, personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_ = 0L;
    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int CHATID_FIELD_NUMBER = 2;
    private long chatId_ = 0L;
    /**
     * <code>int64 chatId = 2;</code>
     * @return The chatId.
     */
    @java.lang.Override
    public long getChatId() {
      return chatId_;
    }

    public static final int ISMEMBER_FIELD_NUMBER = 3;
    private boolean isMember_ = false;
    /**
     * <code>bool isMember = 3;</code>
     * @return The isMember.
     */
    @java.lang.Override
    public boolean getIsMember() {
      return isMember_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (chatId_ != 0L) {
        output.writeInt64(2, chatId_);
      }
      if (isMember_ != false) {
        output.writeBool(3, isMember_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (chatId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, chatId_);
      }
      if (isMember_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isMember_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse)) {
        return super.equals(obj);
      }
      personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse other = (personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (getChatId()
          != other.getChatId()) return false;
      if (getIsMember()
          != other.getIsMember()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + CHATID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChatId());
      hash = (37 * hash) + ISMEMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsMember());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code personal_chat.ValidateUserIsMemberOfPersonalChatResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:personal_chat.ValidateUserIsMemberOfPersonalChatResponse)
        personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return personal_chat.PersonalChat.internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return personal_chat.PersonalChat.internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse.class, personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse.Builder.class);
      }

      // Construct using personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = 0L;
        chatId_ = 0L;
        isMember_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return personal_chat.PersonalChat.internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatResponse_descriptor;
      }

      @java.lang.Override
      public personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse getDefaultInstanceForType() {
        return personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse.getDefaultInstance();
      }

      @java.lang.Override
      public personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse build() {
        personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse buildPartial() {
        personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse result = new personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.chatId_ = chatId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.isMember_ = isMember_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse) {
          return mergeFrom((personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse other) {
        if (other == personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getChatId() != 0L) {
          setChatId(other.getChatId());
        }
        if (other.getIsMember() != false) {
          setIsMember(other.getIsMember());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                chatId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                isMember_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <code>int64 userId = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private long chatId_ ;
      /**
       * <code>int64 chatId = 2;</code>
       * @return The chatId.
       */
      @java.lang.Override
      public long getChatId() {
        return chatId_;
      }
      /**
       * <code>int64 chatId = 2;</code>
       * @param value The chatId to set.
       * @return This builder for chaining.
       */
      public Builder setChatId(long value) {

        chatId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 chatId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chatId_ = 0L;
        onChanged();
        return this;
      }

      private boolean isMember_ ;
      /**
       * <code>bool isMember = 3;</code>
       * @return The isMember.
       */
      @java.lang.Override
      public boolean getIsMember() {
        return isMember_;
      }
      /**
       * <code>bool isMember = 3;</code>
       * @param value The isMember to set.
       * @return This builder for chaining.
       */
      public Builder setIsMember(boolean value) {

        isMember_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool isMember = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsMember() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isMember_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:personal_chat.ValidateUserIsMemberOfPersonalChatResponse)
    }

    // @@protoc_insertion_point(class_scope:personal_chat.ValidateUserIsMemberOfPersonalChatResponse)
    private static final personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse();
    }

    public static personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValidateUserIsMemberOfPersonalChatResponse>
        PARSER = new com.google.protobuf.AbstractParser<ValidateUserIsMemberOfPersonalChatResponse>() {
      @java.lang.Override
      public ValidateUserIsMemberOfPersonalChatResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ValidateUserIsMemberOfPersonalChatResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValidateUserIsMemberOfPersonalChatResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public personal_chat.PersonalChat.ValidateUserIsMemberOfPersonalChatResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023personal_chat.proto\022\rpersonal_chat\"K\n)" +
      "ValidateUserIsMemberOfPersonalChatReques" +
      "t\022\016\n\006userId\030\001 \001(\003\022\016\n\006chatId\030\002 \001(\003\"^\n*Val" +
      "idateUserIsMemberOfPersonalChatResponse\022" +
      "\016\n\006userId\030\001 \001(\003\022\016\n\006chatId\030\002 \001(\003\022\020\n\010isMem" +
      "ber\030\003 \001(\0102\261\001\n\023PersonalChatService\022\231\001\n\"Va" +
      "lidateUserIsMemberOfPersonalChat\0228.perso" +
      "nal_chat.ValidateUserIsMemberOfPersonalC" +
      "hatRequest\0329.personal_chat.ValidateUserI" +
      "sMemberOfPersonalChatResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatRequest_descriptor,
        new java.lang.String[] { "UserId", "ChatId", });
    internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_personal_chat_ValidateUserIsMemberOfPersonalChatResponse_descriptor,
        new java.lang.String[] { "UserId", "ChatId", "IsMember", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
